import * as datefns from 'date-fns';
import { environment } from 'src/environments/environment';

export class CONSTANTS {
  public static ASSETAPPPS = [
    {
      id: 4,
      name: 'GatewayAgent',
      is_start: false,
      is_stop: false,
      is_restart: false,
      is_install: false,
      is_uninstall: false,
      is_update: true,
      display_name: 'Gateway Agent',
      metadata: {},
      deleted: false,
      type: 'system_apps',
    },
    {
      id: 4,
      name: 'MQTTAgent',
      is_start: false,
      is_stop: false,
      is_restart: false,
      is_install: false,
      is_uninstall: false,
      is_update: true,
      display_name: 'MQTT Agent',
      metadata: {},
      deleted: false,
      type: 'system_apps',
    },
    {
      id: 5,
      name: 'CachingAgent',
      is_start: false,
      is_stop: false,
      is_restart: false,
      is_install: false,
      is_uninstall: false,
      is_update: true,
      display_name: 'Caching Agent',
      metadata: {},
      deleted: false,
      type: 'system_apps',
    },
    {
      id: 3,
      name: 'RuleEngine',
      is_start: true,
      is_stop: true,
      is_restart: true,
      is_install: true,
      is_uninstall: true,
      is_update: true,
      display_name: 'Rule Engine',
      metadata: {},
      deleted: false,
      type: 'apps',
    },
    {
      id: 2,
      name: 'ModbusRTUMaster',
      is_start: true,
      is_stop: true,
      is_restart: true,
      is_install: true,
      is_uninstall: true,
      is_update: true,
      display_name: 'Modbus RTU App',
      metadata: {},
      deleted: false,
      type: 'apps',
    },
    {
      id: 1,
      name: 'ModbusTCPMaster',
      is_start: true,
      is_stop: true,
      is_restart: true,
      is_install: true,
      is_uninstall: true,
      is_update: true,
      display_name: 'Modbus TCP App',
      metadata: {},
      deleted: false,
      type: 'apps',
    },
    {
      id: 3,
      name: 'SiemensTCPIP',
      is_start: true,
      is_stop: true,
      is_restart: true,
      is_install: true,
      is_uninstall: true,
      is_update: true,
      display_name: 'Siemens TCP/IP App',
      metadata: {},
      deleted: false,
      type: 'apps',
    },
    {
      id: 3,
      name: 'N_BlueNRG',
      is_start: true,
      is_stop: true,
      is_restart: true,
      is_install: true,
      is_uninstall: true,
      is_update: true,
      display_name: 'N_BlueNRG',
      metadata: {},
      deleted: false,
      type: 'apps',
    },
    {
      id: 8,
      name: 'N_AIoTInputs',
      is_start: true,
      is_stop: true,
      is_restart: true,
      is_install: true,
      is_uninstall: true,
      is_update: true,
      display_name: 'N_AIoTInputs',
      metadata: {},
      deleted: false,
      type: 'apps',
    },
    {

      id: 9,
      name: 'BLE_Engine',
      is_start: false,
      is_stop: false,
      is_restart: false,
      is_install: false,
      is_uninstall: false,
      is_update: true,
      display_name: 'BLE_Engine',
      metadata: {},
      deleted: false,
      type: 'system_apps',
    },
  ];

  public static PROTOCOLS = [
    {
      id: 1,
      asset_model: 'IoT Asset',
      name: 'IP Asset (WiFi)',
      display_name: 'IP Asset (WiFi)',
      cloud_connectivity: [
        'IP Asset -> Azure IoT Hub SDK -> WiFi -> Cloud',
        'IP Asset -> MQTT Client -> WiFi -> Cloud',
      ],
      metadata: {},
      deleted: false,
    },
    {
      id: 2,
      asset_model: 'IoT Asset',
      name: 'IP Asset (SIM)',
      display_name: 'IP Asset (SIM)',
      cloud_connectivity: ['IP Asset -> Azure IoT Hub SDK -> SIM -> Cloud', 'IP Asset -> MQTT Client -> SIM -> Cloud'],
      metadata: {},
      deleted: false,
    },
    {
      id: 3,
      asset_model: 'IoT Gateway',
      name: 'IP Gateway (WiFi)',
      display_name: 'IP Gateway (WiFi)',
      cloud_connectivity: [
        'IP Gateway -> Azure IoT Hub SDK -> WiFi -> Cloud',
        'IP Gateway -> MQTT Client -> WiFi -> Cloud',
      ],
      metadata: {},
      deleted: false,
    },
    {
      id: 4,
      asset_model: 'IoT Gateway',
      name: 'IP Gateway (SIM)',
      display_name: 'IP Gateway (SIM)',
      cloud_connectivity: [
        'IP Gateway -> Azure IoT Hub SDK -> SIM -> Cloud',
        'IP Gateway -> MQTT Client -> SIM -> Cloud',
      ],
      metadata: {},
      deleted: false,
    },
    {
      id: 5,
      asset_model: 'Legacy Asset',
      name: 'ModbusTCPMaster',
      display_name: 'Modbus TCP',
      cloud_connectivity: ['ModBus TCP Asset -> IoT Gateway -> Azure IoT Hub SDK -> Cloud'],
      metadata: { app: 'ModbusTCPMaster' },
      deleted: false,
    },
    {
      id: 6,
      asset_model: 'Legacy Asset',
      name: 'ModbusRTUMaster',
      display_name: 'Modbus RTU',
      cloud_connectivity: ['ModBus RTU Asset -> IoT Gateway -> Azure IoT Hub SDK -> Cloud'],
      metadata: { app: 'ModbusRTUMaster' },
      deleted: false,
    },
    {
      id: 7,
      asset_model: 'Legacy Asset',
      name: 'SiemensTCPIP',
      display_name: 'Siemens TCP/IP',
      cloud_connectivity: ['Siemens TCP/IP Asset -> IoT Gateway -> Azure IoT Hub SDK -> Cloud'],
      metadata: { app: 'SiemensTCPIP' },
      deleted: false,
    },
    {
      id: 8,
      asset_model: 'Legacy Asset',
      name: 'BlueNRG',
      display_name: 'BlueNRG',
      cloud_connectivity: ['BLE Asset -> IoT Gateway -> Azure IoT Hub SDK -> Cloud'],
      metadata: { app: 'N_BlueNRG' },
      deleted: false,
    },
    {
      id: 9,
      asset_model: 'Legacy Asset',
      name: 'AIoTInputs',
      display_name: 'AIoTInputs',
      cloud_connectivity: ['AIoT Asset -> IoT Gateway -> Azure IoT Hub SDK -> Cloud'],
      metadata: { app: 'N_AIoTInputs' },
      deleted: false,
    },
  ];

  public static DEFAULT_PRIVILEGES = {
    APMM: {
      display_name: 'App Management - Manage',
      enabled: true,
    },
    APMV: {
      display_name: 'App Management - View',
      enabled: true,
    },
    ASCMM: {
      display_name: 'Asset Campaign Management - Manage',
      enabled: true,
    },
    ASCMV: {
      display_name: 'Asset Campaign Management - View',
      enabled: true,
    },
    ASMD: {
      display_name: 'Asset Management - Deprovision',
      enabled: true,
    },
    ASMM: {
      display_name: 'Asset Management - Manage',
      enabled: true,
    },
    ASMMM: {
      display_name: 'Asset Model Management - Manage',
      enabled: true,
    },
    ASMMV: {
      display_name: 'Asset Model Management - View',
      enabled: true,
    },
    ASMP: {
      display_name: 'Asset Management - Provision',
      enabled: true,
    },
    ASMED: {
      display_name: 'Asset Management - Enable/Disable',
      enabled: true,
    },
    ASMS: {
      display_name: 'Asset Management - Setup',
      enabled: true,
    },
    ASMV: {
      display_name: 'Asset Management - View',
      enabled: true,
    },
    ASMVC: {
      display_name: 'Asset Management - View Creds',
      enabled: true,
    },
    ASMW: {
      display_name: 'App Management - WhiteList Asset',
      enabled: true,
    },
    RCC: {
      display_name: 'Remote Control - Control',
      enabled: true,
    },
    RCP: {
      display_name: 'Remote Control - Purge',
      enabled: true,
    },
    RCV: {
      display_name: 'Remote Control - View',
      enabled: true,
    },
    RKPIM: {
      display_name: 'Rules & KPIs - Manage',
      enabled: true,
    },
    RKPIV: {
      display_name: 'Rules & KPIs - View',
      enabled: true,
    },
    RMM: {
      display_name: 'Remote Monitoring - Manage',
      enabled: true,
    },
    RMV: {
      display_name: 'Remote Monitoring - View',
      enabled: true,
    },
    RSM: {
      display_name: 'Reports - Subscription Management',
      enabled: true,
    },
    RV: {
      display_name: 'Reports - View',
      enabled: true,
    },
    UMM: {
      display_name: 'User Management - Manage',
      enabled: true,
    },
    UMV: {
      display_name: 'User Management - View',
      enabled: true,
    },
    WASMP: {
      display_name: 'Whitelisting Asset Management - Provision',
      enabled: true
    },
    WASMV: {
      display_name: 'Whitelisting Asset Management - View',
      enabled: true
    },
    WASMI: {
      display_name: 'Whitelisting Asset Management - Import',
      enabled: true
    }
  };

  public static PRIVILEGE_GROUPS = {
    'App Management': ['APMV', 'APMM'],
    'Assets': ['ASMV', 'ASMVC', 'ASMM', 'ASMS'],
    'Asset Management': ['ASMP', 'ASMD', 'ASMED'],
    'Asset Campaign Management': ['ASCMV', 'ASCMM'],
    'Asset Model Management': ['ASMMV', 'ASMMM'],
    'Remote Control': ['RCV', 'RCC', 'RCP'],
    'Rules & KPIs': ['RKPIV', 'RKPIM'],
    'Remote Monitoring': ['RMV', 'RMM'],
    'Reports': ['RV', 'RSM'],
    'User Management': ['UMV', 'UMM'],
    'Whitelisting Asset Management' : ['WASMI','WASMP','WASMV']
  };

  public static SIDE_MENU_LIST = [
    {
      page: 'Home',
      system_name: 'Home',
      url: 'applications/:appName',
      display_name: 'Home',
      icon: 'fas fa-fw fa-home',
      visible: true,
      exactMatch: true,
      privileges_required: ['ASMV'],
      showAccordion: [
        {
          name: 'Title',
          value: 'Home',
        },
      ],
      priority: 1,
    },
    {
      page: 'Live Data',
      system_name: 'Live Data',
      url: 'applications/:appName/dashboard',
      display_name: 'Live Data',
      icon: 'fa fa-fw fa-chart-bar',
      visible: true,
      exactMatch: true,
      privileges_required: ['ASMV', 'RMV'],
      showAccordion: [
        {
          name: 'Title',
          value: 'Live Data',
        },
      ],
      priority: 1,
    }, 
    {
      page: 'GateWay Monitoring',
      system_name: 'Gateway Monitoring',
      url: 'applications/:appName/gateway-monitoring',
      display_name: 'Gateway Monitoring',
      icon: 'fa fa-fw fa-desktop fas',
      visible: true,
      exactMatch: true,
      privileges_required: ['GTMO'],
      showAccordion: [
        {
          name: 'Title',
          value: 'Gateway Monitoring',
        },
      ],
      priority: 1,
    },   
    {
      page: 'Live Alerts',
      system_name: 'Live Alerts',
      url: 'applications/:appName/alerts/visualization',
      display_name: 'Live Alerts',
      icon: 'fa fa-fw fa-bell',
      exactMatch: true,
      privileges_required: ['ASMV', 'RMV'],
      visible: true,
      showAccordion: [
        {
          name: 'Title',
          value: 'Live Alerts',
        },
      ],
      priority: 1,
    },
    {
      page: 'Assets',
      system_name: 'Assets',
      url: 'applications/:appName/assets',
      display_name: 'Assets',
      for_admin_only: true,
      exactMatch: true,
      icon: 'fab fa-fw fa-mixcloud',
      privileges_required: ['ASMV'],
      visible: true,
      showAccordion: [
        { name: 'Title', value: 'Assets' },
        { name: 'Records Limit', value: 20, type: 'number' },
        { name: 'IoT Assets', type: 'checkbox', value: true },
        { name: 'Legacy Assets', type: 'checkbox', value: true },
        { name: 'IoT Gateways', type: 'checkbox', value: true },
        { name: 'IoT Asset', value: 'IoT Asset' },
        { name: 'IoT Assets Tab Name', value: 'IoT Assets' },
        { name: 'IoT Assets Table Key Name', value: 'Asset' },
        { name: 'IoT Gateway', value: 'IoT Gateway' },
        { name: 'IoT Gateways Tab Name', value: 'IoT Gateways' },
        { name: 'IoT Gateways Table Key Name', value: 'Gateway' },
        { name: 'Legacy Asset', value: 'Legacy Asset' },
        { name: 'Legacy Assets Tab Name', value: 'Legacy Assets' },
        { name: 'Legacy Assets Table Key Name', value: 'Asset' },
      ],
      priority: 1,
    },
    {
      page: 'Asset Management',
      system_name: 'Asset Management',
      url: 'applications/:appName/assets/management',
      display_name: 'Asset Management',
      for_admin_only: true,
      exactMatch: true,
      icon: 'fa fa-fw fa-cogs',
      visible: true,
      showAccordion: [{ name: 'Title', value: 'Asset Management' }],
      privileges_required: ['ASMP', 'ASMD', 'ASMED','WASMV'],
      priority: 1,
    },
    {
      page: 'Asset Whitelist',
      system_name: 'Asset Whitelist',
      url: 'applications/:appName/assets/whitelist',
      display_name: 'Asset Whitelist',
      for_admin_only: true,
      exactMatch: true,
      icon: 'fa fa-fw fa-tasks',
      visible: true,
      showAccordion: [
        { name: 'Title', value: 'Asset Whitelist' },
        { name: 'Records Limit', value: 20, type: 'number' },
        { name: 'IoT Assets', type: 'checkbox', value: true },
        { name: 'Legacy Assets', type: 'checkbox', value: true },
        { name: 'IoT Gateways', type: 'checkbox', value: true },
        { name: 'IoT Asset', value: 'IoT Asset' },
        { name: 'IoT Assets Tab Name', value: 'IoT Assets' },
        { name: 'IoT Assets Table Key Name', value: 'Asset' },
        { name: 'IoT Gateway', value: 'IoT Gateway' },
        { name: 'IoT Gateways Tab Name', value: 'IoT Gateways' },
        { name: 'IoT Gateways Table Key Name', value: 'Gateway' },
        { name: 'Legacy Asset', value: 'Legacy Asset' },
        { name: 'Legacy Assets Tab Name', value: 'Legacy Assets' },
        { name: 'Legacy Assets Table Key Name', value: 'Asset' },
      ],
      privileges_required: ['WASMV'],
      priority: 1,
    },
    {
      page: 'Asset Models',
      system_name: 'Asset Models',
      url: 'applications/:appName/assets/model',
      display_name: 'Asset Models',
      exactMatch: true,
      icon: 'icon icon-cubes',
      visible: true,
      showAccordion: [
        { name: 'Title', value: 'Models' },
        { name: 'Table Key Name', value: 'Model' },
      ],
      privileges_required: ['ASMMV'],
      priority: 1,
    },
    {
      page: 'Reports',
      system_name: 'Reports',
      url: 'applications/:appName/reports',
      display_name: 'Reports',
      icon: 'fa fa-fw fa-chart-line',
      visible: true,
      exactMatch: true,
      showAccordion: [
        { name: 'Title', value: 'Reports' },
        { name: 'Records Limit', value: 100, type: 'number' },
      ],
      privileges_required: ['RV'],
      priority: 1,
    },
    {
      page: 'Campaigns',
      system_name: 'Campaigns',
      url: 'applications/:appName/campaigns',
      display_name: 'Campaigns',
      icon: 'fa fa-fw fa-object-group',
      visible: true,
      exactMatch: true,
      privileges_required: ['ASCMV','ASCMM'],
      showAccordion: [{ name: 'Title', value: 'Campaigns' }],
      priority: 1,
    },
    {
      page: 'Maintenance',
      system_name: 'Maintenance',
      url: 'applications/:appName/maintenance',
      display_name: 'Maintenance',
      icon: 'fa fa-fw fa-solid fa-wrench',
      visible: true,
      exactMatch: true,
      maintenance_module: true,
      privileges_required: ['MNTCV'],
      showAccordion: [{ name: 'Title', value: 'Maintenance' }],
      priority: 1,
    },

    
  ];

  public static ASSET_CONTROL_PANEL_SIDE_MENU_LIST = [
    {
      page: 'manage',
      system_name: 'Manage',
      url: null,
      display_name: 'Manage',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'overview',
      system_name: 'Overview',
      url: '#asset_overview',
      display_name: 'Overview',
      icon: 'fa fa-fw fa-life-ring',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'access_control',
      system_name: 'Access Control',
      url: '#asset_access_control',
      display_name: 'Access Control (IAM)',
      icon: 'fa fa-fw fa-users',
      visible: true,
      isTitle: false,
      showAccordion: [],
      privileges_required: [],
      accordion_value: {},
    },
    {
      page: 'tags',
      system_name: 'Tags',
      url: '#asset_tags',
      display_name: 'Tags',
      icon: 'fa fa-fw fa-tags',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [{ name: 'Delete all', key: 'delete' }],
      accordion_value: { delete: true },
    },
    {
      page: 'slave_info',
      system_name: 'Sensor / Source / Slave Info',
      url: '#asset_model_slave_info',
      display_name: 'Sensor / Source / Slave Info',
      icon: 'fa fa-fw fa-user-secret',
      visible: true,
      privileges_required: ['ASMS'],
      isTitle: false,
    },
    {
      page: 'package_management',
      system_name: 'Software Packages',
      url: '#asset_package_management',
      display_name: 'Software Packages',
      icon: 'fa fa-fw fa-file',
      privileges_required: ['ASMMV'],
      visible: true,
      isTitle: false,
    },
    {
      page: 'setup',
      system_name: 'Setup',
      url: '#asset_setup',
      display_name: 'Setup',
      icon: 'fa fa-fw fa-cog',
      visible: true,
      isTitle: false,
      privileges_required: ['RCC'],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'uptime',
      system_name: 'Uptime',
      url: '#asset_uptime',
      display_name: 'Uptime',
      icon: 'fa fa-fw fa-history',
      visible: true,
      isTitle: false,
      privileges_required: ['ASMP', 'ASMD', 'ASMED','WASMV'],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'd2c',
      system_name: 'Monitor (D2C)',
      url: null,
      display_name: 'Monitor (D2C)',
      icon: null,
      visible: true,
      isTitle: true,
    },
    // {
    //   page: 'heartbeat',
    //   system_name: 'Heartbeat',
    //   url: '#asset_heartbeat',
    //   display_name: 'Heartbeat',
    //   icon: 'fa fa-fw fa-heartbeat',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    {
      page: 'current_config',
      system_name: 'Current Configuration',
      url: '#asset_current_config',
      display_name: 'Current Configuration',
      icon: 'fa fa-fw fa-cog',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'config_history',
      system_name: 'Configuration History',
      url: '#asset_config_history',
      display_name: 'Configuration History',
      icon: 'fa fa-fw fa-history',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'asset_life_cycle',
      system_name: 'Life Cycle Events',
      url: '#asset_life_cycle_events',
      display_name: 'Life Cycle Events',
      icon: 'fa fa-fw fa-heartbeat',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'notifications',
      system_name: 'Notifications',
      url: '#asset_notifications',
      display_name: 'Notifications',
      icon: 'fa fa-fw fa-bell',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'alerts',
      system_name: 'Alert',
      url: '#asset_alerts',
      display_name: 'Alert',
      icon: 'fa fa-fw fa-bolt',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    // {
    //   page: 'alertendevents',
    //   system_name: 'Alert End Events',
    //   url: '#asset_alert_end_events',
    //   display_name: 'Alert End Events',
    //   icon: 'fa fa-fw fa-hourglass-end',
    //   visible: true,
    //   isTitle: false,
    //   privileges_required: ['RMV'],
    //   showAccordion: [],
    //   accordion_value: {},
    // },
    {
      page: 'telemetry',
      system_name: 'Telemetry',
      url: '#asset_telemetry',
      display_name: 'Telemetry',
      icon: 'fa fa-fw fa-history',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    // {
    //   page: 'error',
    //   system_name: 'Error',
    //   url: '#asset_error',
    //   display_name: 'Error',
    //   icon: 'fa fa-fw fa-exclamation-triangle',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    // {
    //   page: 'battery_message',
    //   system_name: 'Battery',
    //   url: '#asset_battery_message',
    //   display_name: 'Battery',
    //   icon: 'fa fa-fw fa-battery-full',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    {
      page: 'logs',
      system_name: 'Logs',
      url: '#asset_logs',
      display_name: 'Logs',
      icon: 'fa fa-fw fa-file',
      visible: true,
      privileges_required: [],
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'alert_conditioning',
      system_name: 'Alert Conditioning',
      url: '#asset_alert_conditioning',
      display_name: 'Alert Conditioning',
      icon: 'fa fa-fw fa-exclamation-triangle',
      privileges_required: [],
      visible: true,
      isTitle: false,
    },
    {
      page: 'cached_alerts',
      system_name: 'Cached Alerts',
      url: '#asset_cached_alerts',
      display_name: 'Cached Alerts',
      icon: 'fa fa-fw fa-bolt',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'cached_telemetry',
      system_name: 'Cached Telemetry',
      url: '#asset_cached_telemetry',
      display_name: 'Cached Telemetry',
      icon: 'fa fa-fw fa-globe',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    // {
    //   page: 'other',
    //   system_name: 'Other',
    //   url: '#asset_other',
    //   display_name: 'Other',
    //   icon: 'fa fa-fw fa-globe',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    {
      page: 'c2d',
      system_name: 'Control (C2D)',
      url: null,
      display_name: 'Control (C2D)',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'control_widgets',
      system_name: 'Control / Configure',
      url: '#asset_control_widgets',
      display_name: 'Control / Configure',
      icon: 'fa fa-fw fa-angle-right',
      visible: true,
      isTitle: false,
      privileges_required: ['RCV'],
      showAccordion: [
        { name: 'Configuration', key: 'configuration' },
        { name: 'Control', key: 'control' },
        { name: 'Purge', key: 'purge' },
      ],
      accordion_value: { configuration: true, control: true, purge: true },
    },
    {
      page: 'compute',
      system_name: 'Compute',
      url: 'null',
      display_name: 'Compute',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'cloud_derived_properties',
      system_name: 'Cloud Derived Properties',
      url: '#asset_stream_processing',
      display_name: 'Cloud Derived Properties',
      icon: 'fa fa-fw fa-globe',
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'derived_kpis',
      system_name: 'Derived KPIs',
      url: '#asset_derived_kpis',
      display_name: 'Derived KPIs',
      icon: 'fa fa-fw fa-angle-right',
      visible: true,
      isTitle: false,
      privileges_required: ['RKPIV'],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'rules',
      system_name: 'Rules',
      url: '#asset_rules',
      display_name: 'Rules',
      icon: 'fa fa-fw fa-archive',
      visible: true,
      isTitle: false,
      privileges_required: ['RKPIV'],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'visualize',
      system_name: 'Visualize',
      url: 'null',
      display_name: 'Visualize',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'trend-analysis',
      system_name: 'Trend Analysis',
      url: '#asset_trend_analysis',
      display_name: 'Telemetry Trend Analysis',
      icon: 'fa fa-fw fa-area-chart',
      privileges_required: ['ASMMV'],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'alert-visualization',
      system_name: 'Alert Visualization',
      url: '#asset_alert_visualization',
      display_name: 'Alert Visualization',
      icon: 'fa fa-fw fa-bar-chart',
      visible: true,
      isTitle: false,
      privileges_required: ['ASMMV'],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'maintain',
      system_name: 'Maintain',
      url: null,
      display_name: 'Maintain',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'mttr',
      system_name: 'MTTR',
      url: '#asset_mttr',
      display_name: 'MTTR',
      icon: 'fa fa-fw fa-clock',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'mtbf',
      system_name: 'MTBF',
      url: '#asset_mtbf',
      display_name: 'MTBF',
      icon: 'fa fa-fw fa-calendar-o',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'maintenance_schedule',
      system_name: 'Maintenance Schedules',
      url: '#asset_maintenance_schedule',
      display_name: 'Maintenance Schedules',
      icon: 'fa fa-fw fa-wrench',
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'predictions',
      system_name: 'Predictions',
      url: '#asset_predictions',
      display_name: 'Predictions',
      icon: 'fa fa-fw fa-magic',
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    
  ];

  public static LEGACY_ASSET_CONTROL_PANEL_SIDE_MENU_LIST = [
    {
      page: 'manage',
      system_name: 'Manage',
      url: null,
      display_name: 'Manage',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'overview',
      system_name: 'Overview',
      url: '#asset_overview',
      display_name: 'Overview',
      icon: 'fa fa-fw fa-life-ring',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'access_control',
      system_name: 'Access Control',
      url: '#asset_access_control',
      display_name: 'Access Control (IAM)',
      icon: 'fa fa-fw fa-users',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'tags',
      system_name: 'Tags',
      url: '#asset_tags',
      display_name: 'Tags',
      icon: 'fa fa-fw fa-tags',
      visible: true,
      isTitle: false,
      privileges_required: [],
      showAccordion: [{ name: 'Delete all', key: 'delete' }],
      accordion_value: { delete: true },
    },
    {
      page: 'slave_info',
      system_name: 'Sensor / Source / Slave Info',
      url: '#asset_slave_info',
      display_name: 'Sensor / Source / Slave Info',
      icon: 'fa fa-fw fa-user-secret',
      privileges_required: ['ASMS'],
      visible: true,
      isTitle: false,
    },
    // {
    //   page: 'package_management',
    //   system_name: 'Software Packages',
    //   url: '#asset_package_management',
    //   display_name: 'Software Packages',
    //   icon: 'fa fa-fw fa-file',
    //   visible: true,
    //   isTitle: false
    // },
    {
      page: 'setup',
      system_name: 'Setup',
      url: '#asset_setup',
      display_name: 'Setup',
      icon: 'fa fa-fw fa-cog',
      privileges_required: ['RCC'],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'd2c',
      system_name: 'Monitor (D2C)',
      url: null,
      display_name: 'Monitor (D2C)',
      icon: null,
      visible: true,
      isTitle: true,
    },
    // {
    //   page: 'heartbeat',
    //   system_name: 'Heartbeat',
    //   url: '#asset_heartbeat',
    //   display_name: 'Heartbeat',
    //   icon: 'fa fa-fw fa-heartbeat',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    {
      page: 'notifications',
      system_name: 'Notifications',
      url: '#asset_notifications',
      display_name: 'Notifications',
      icon: 'fa fa-fw fa-bell',
      visible: true,
      privileges_required: [],
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'alerts',
      system_name: 'Alert',
      url: '#asset_alerts',
      display_name: 'Alert',
      icon: 'fa fa-fw fa-bolt',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    // {
    //   page: 'alertendevents',
    //   system_name: 'Alert End Events',
    //   url: '#asset_alert_end_events',
    //   display_name: 'Alert End Events',
    //   icon: 'fa fa-fw fa-hourglass-end',
    //   privileges_required: ['RMV'],
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {},
    // },
    {
      page: 'telemetry',
      system_name: 'Telemetry',
      url: '#asset_telemetry',
      display_name: 'Telemetry',
      icon: 'fa fa-fw fa-history',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    // {
    //   page: 'error',
    //   system_name: 'Error',
    //   url: '#asset_error',
    //   display_name: 'Error',
    //   icon: 'fa fa-fw fa-exclamation-triangle',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    // {
    //   page: 'battery_message',
    //   system_name: 'Battery',
    //   url: '#asset_battery_message',
    //   display_name: 'Battery',
    //   icon: 'fa fa-fw fa-battery-full',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    {
      page: 'logs',
      system_name: 'Logs',
      url: '#asset_logs',
      privileges_required: [],
      display_name: 'Logs',
      icon: 'fa fa-fw fa-file',
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'alert_conditioning',
      system_name: 'Alert Conditioning',
      url: '#asset_alert_conditioning',
      display_name: 'Alert Conditioning',
      icon: 'fa fa-fw fa-exclamation-triangle',
      privileges_required: [],
      visible: true,
      isTitle: false,
    },
    // {
    //   page: 'other',
    //   system_name: 'Other',
    //   url: '#asset_other',
    //   display_name: 'Other',
    //   icon: 'fa fa-fw fa-globe',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    {
      page: 'c2d',
      system_name: 'Control (C2D)',
      url: null,
      display_name: 'Control (C2D)',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'control_widgets',
      system_name: 'Control / Configure',
      url: '#asset_control_widgets',
      display_name: 'Control / Configure',
      icon: 'fa fa-fw fa-angle-right',
      visible: true,
      isTitle: false,
      privileges_required: ['RCV'],
      showAccordion: [
        { name: 'Configuration', key: 'configuration' },
        { name: 'Control', key: 'control' },
        { name: 'Purge', key: 'purge' },
      ],
      accordion_value: { configuration: true, purge: true, control: true },
    },
    {
      page: 'compute',
      system_name: 'Compute',
      url: 'null',
      display_name: 'Compute',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'cloud_derived_properties',
      system_name: 'Cloud Derived Properties',
      url: '#asset_stream_processing',
      display_name: 'Cloud Derived Properties',
      icon: 'fa fa-fw fa-globe',
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'derived_kpis',
      system_name: 'Derived KPIs',
      url: '#asset_derived_kpis',
      display_name: 'Derived KPIs',
      icon: 'fa fa-fw fa-angle-right',
      privileges_required: ['RKPIV'],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'rules',
      system_name: 'Rules',
      url: '#asset_rules',
      display_name: 'Rules',
      icon: 'fa fa-fw fa-archive',
      privileges_required: ['RKPIV'],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'visualization',
      system_name: 'Visualize',
      url: 'null',
      display_name: 'Visualize',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'trend-analysis',
      system_name: 'Trend Analysis',
      url: '#asset_trend_analysis',
      display_name: 'Telemetry Trend Analysis',
      icon: 'fa fa-fw fa-area-chart',
      privileges_required: ['ASMMV'],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'alert-visualization',
      system_name: 'Alert Visualization',
      url: '#asset_alert_visualization',
      display_name: 'Alert Visualization',
      icon: 'fa fa-fw fa-bar-chart',
      privileges_required: ['ASMMV'],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'maintain',
      system_name: 'Maintain',
      url: null,
      display_name: 'Maintain',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'mttr',
      system_name: 'MTTR',
      url: '#asset_mttr',
      display_name: 'MTTR',
      icon: 'fa fa-fw fa-wrench',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'mtbf',
      system_name: 'MTBF',
      url: '#asset_mtbf',
      display_name: 'MTBF',
      icon: 'fa fa-fw fa-wrench',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'maintenance_schedule',
      system_name: 'Maintenance Schedules',
      url: '#asset_maintenance_schedule',
      display_name: 'Maintenance Schedules',
      icon: 'fa fa-fw fa-wrench',
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'predictions',
      system_name: 'Predictions',
      url: '#asset_predictions',
      display_name: 'Predictions',
      icon: 'fa fa-fw fa-wrench',
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
  ];

  public static GATEWAY_DIAGNOSIS_PANEL_SIDE_MENU_LIST = [
    {
      page: 'manage',
      system_name: 'Manage',
      url: null,
      display_name: 'Manage',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'overview',
      system_name: 'Overview',
      url: '#asset_overview',
      display_name: 'Overview',
      icon: 'fa fa-fw fa-life-ring',
      visible: true,
      privileges_required: [],
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'tags',
      system_name: 'Tags',
      url: '#asset_tags',
      display_name: 'Tags',
      icon: 'fa fa-fw fa-tags',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [{ name: 'Delete all', key: 'delete' }],
      accordion_value: { delete: true },
    },
    {
      page: 'package_management',
      system_name: 'Software Packages',
      url: '#asset_package_management',
      display_name: 'Software Packages',
      icon: 'fa fa-fw fa-file',
      privileges_required: ['ASMMV'],
      visible: true,
      isTitle: false,
    },
    {
      page: 'setup',
      system_name: 'Setup',
      url: '#asset_setup',
      display_name: 'Setup',
      icon: 'fa fa-fw fa-cog',
      privileges_required: ['RCC'],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'd2c',
      system_name: 'Monitor (D2C)',
      url: null,
      display_name: 'Monitor (D2C)',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'current_config',
      system_name: 'Current Configuration',
      url: '#asset_current_config',
      display_name: 'Current Configuration',
      icon: 'fa fa-fw fa-cog',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'config_history',
      system_name: 'Configuration History',
      url: '#asset_config_history',
      display_name: 'Configuration History',
      icon: 'fa fa-fw fa-history',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'notifications',
      system_name: 'Notifications',
      url: '#asset_notifications',
      display_name: 'Notifications',
      icon: 'fa fa-fw fa-bell',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'asset_life_cycle',
      system_name: 'Life Cycle Events',
      url: '#asset_life_cycle_events',
      display_name: 'Life Cycle Events',
      icon: 'fa fa-fw fa-heartbeat',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'cached_alerts',
      system_name: 'Cached Alerts',
      url: '#asset_cached_alerts',
      display_name: 'Cached Alerts',
      icon: 'fa fa-fw fa-bolt',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'cached_telemetry',
      system_name: 'Cached Telemetry',
      url: '#asset_cached_telemetry',
      display_name: 'Cached Telemetry',
      icon: 'fa fa-fw fa-globe',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'logs',
      system_name: 'Logs',
      url: '#asset_logs',
      display_name: 'Logs',
      icon: 'fa fa-fw fa-file',
      visible: true,
      privileges_required: [],
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    {
      page: 'count',
      system_name: 'Telemetry Count',
      url: '#asset_count',
      display_name: 'Telemetry Count',
      icon: 'fa fa-fw fa-calculator',
      privileges_required: [],
      visible: true,
      isTitle: false,
      showAccordion: [],
      accordion_value: {},
    },
    // {
    //   page: 'error',
    //   system_name: 'Error',
    //   url: '#asset_error',
    //   display_name: 'Error',
    //   icon: 'fa fa-fw fa-exclamation-triangle',
    //   visible: true,
    //   isTitle: false,
    //   showAccordion: [],
    //   accordion_value: {}
    // },
    {
      page: 'c2d',
      system_name: 'Control(C2D)',
      url: null,
      display_name: 'Control(C2D)',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'control_widgets',
      system_name: 'Control/Configure',
      url: '#asset_control_widgets',
      display_name: 'Control/Configure',
      icon: 'fa fa-fw fa-angle-right',
      privileges_required: ['RCV'],
      visible: true,
      isTitle: false,
      showAccordion: [
        { name: 'Configuration', key: 'configuration' },
        { name: 'Control', key: 'control' },
        { name: 'Purge', key: 'purge' },
      ],
      accordion_value: { configuration: true, purge: true, control: true },
    },
  ];

  public static MODEL_CONTROL_PANEL_SIDE_MENU_LIST = [
    {
      page: 'manage',
      system_name: 'Manage',
      url: null,
      display_name: 'Manage',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'overview',
      system_name: 'Overview',
      url: '#asset_model_overview',
      display_name: 'Overview',
      icon: 'fa fa-fw fa-life-ring',
      visible: true,
      isTitle: false,
    },
    {
      page: 'tags',
      system_name: 'Tags',
      url: '#asset_model_tags',
      display_name: 'Tags',
      icon: 'fa fa-fw fa-tags',
      visible: true,
      isTitle: false,
    },
    {
      page: 'package_management',
      system_name: 'Software Packages',
      url: '#asset_model_package_management',
      display_name: 'Software Packages',
      icon: 'fa fa-fw fa-file',
      visible: true,
      isTitle: false,
    },
    {
      page: 'settings',
      system_name: 'Setup',
      url: '#asset_model_settings',
      display_name: 'Setup',
      icon: 'fa fa-fw fa-cog',
      visible: true,
      isTitle: false,
    },
    {
      page: 'd2c',
      system_name: 'Monitor',
      url: null,
      display_name: 'Monitor',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'slave_info',
      system_name: 'Sensor / Source / Slave Info',
      url: '#asset_model_slave_info',
      display_name: 'Sensor / Source / Slave Info',
      icon: 'fa fa-fw fa-user-secret',
      visible: true,
      isTitle: false,
    },
    {
      page: 'measured_properties',
      system_name: 'Measured Properties',
      url: '#asset_model_properties',
      display_name: 'Measured Properties',
      icon: 'fa fa-fw fa-history',
      visible: true,
      isTitle: false,
    },
    {
      page: 'edge_derived_properties',
      system_name: 'Edge Derived Properties',
      url: '#asset_model_properties',
      display_name: 'Edge Derived Properties',
      icon: 'fa fa-fw fa-retweet',
      visible: true,
      isTitle: false,
    },
    {
      page: 'controllable_properties',
      system_name: 'Controllable Properties',
      url: '#asset_model_properties',
      display_name: 'Controllable Properties',
      icon: 'fa fa-fw fa-edit',
      visible: true,
      isTitle: false,
    },
    {
      page: 'configurable_properties',
      system_name: 'Configurable Properties',
      url: '#asset_model_properties',
      display_name: 'Configurable Properties',
      icon: 'fa fa-fw fa-book',
      visible: true,
      isTitle: false,
    },

    {
      page: 'alert_conditioning',
      system_name: 'Alert Conditioning',
      url: '#asset_model_alert_conditioning',
      display_name: 'Alert Conditioning',
      icon: 'fa fa-fw fa-exclamation-triangle',
      visible: true,
      isTitle: false,
    },
    {
      page: 'c2d',
      system_name: 'Control',
      url: null,
      display_name: 'Control',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'direct_methods',
      system_name: 'Direct Methods',
      url: '#asset_model_methods',
      display_name: 'Direct Methods',
      icon: 'fa fa-fw fa-archive',
      visible: true,
      isTitle: false,
    },
    {
      page: 'configuration_widgets',
      system_name: 'Configuration Widgets',
      url: '#asset_model_configuration_widgets',
      display_name: 'Configuration Widgets',
      icon: 'fa fa-fw fa-cog',
      visible: true,
      isTitle: false,
    },
    {
      page: 'control_widgets',
      system_name: 'Control Widgets',
      url: '#asset_model_control_widgets',
      display_name: 'Control Widgets',
      icon: 'fa fa-fw fa-angle-right',
      visible: true,
      isTitle: false,
    },
    {
      page: 'compute',
      system_name: 'Compute',
      url: null,
      display_name: 'Compute',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'cloud_derived_properties',
      system_name: 'Cloud Derived Properties',
      url: '#asset_model_stream_processing',
      display_name: 'Cloud Derived Properties',
      icon: 'fa fa-fw fa-microchip',
      visible: true,
      isTitle: false,
    },
    {
      page: 'derived_kpis',
      system_name: 'Derived KPIs',
      url: '#asset_model_derived_kpis',
      display_name: 'Derived KPIs',
      icon: 'fa fa-fw fa-retweet',
      visible: true,
      isTitle: false,
    },
    {
      page: 'rules',
      system_name: 'Rules',
      url: '#asset_model_rules',
      display_name: 'Rules',
      icon: 'fa fa-fw fa-archive',
      visible: true,
      privileges_required: ['RKPIV'],
      isTitle: false,
    },
    // {
    //   page: 'addrules',
    //   system_name: 'addRules',
    //   url: '#asset_model_add_rules',
    //   display_name: 'AddRules',
    //   icon: 'fa fa-fw fa-archive',
    //   visible: true,
    //   isTitle: false
    // },
    {
      page: 'visualization',
      system_name: 'Visualize',
      url: 'null',
      display_name: 'Visualize',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'layout',
      system_name: 'Visualization Widgets',
      url: '#asset_model_layout',
      display_name: 'Visualization Widgets',
      icon: 'fa fa-fw fa-bar-chart',
      visible: true,
      isTitle: false,
      showAccordion: [{ name: 'Widget', key: 'widget', type: 'text' }],
      accordion_value: { widget: 'Widget' },
    },
    {
      page: 'reference_material',
      system_name: 'Reference Material',
      url: null,
      display_name: 'Reference Material',
      icon: null,
      visible: true,
      isTitle: true,
    },
    {
      page: 'reference_material',
      system_name: 'Documents',
      url: '#asset_model_reference_material',
      display_name: 'Documents',
      icon: 'fa fa-fw fa-file',
      visible: true,
      isTitle: false,
    },
    {
      page: 'alert_acknowledgement_reasons',
      system_name: 'Alert Acknowledgement Reasons',
      url: '#asset_model_alert_acknowledgement_reasons',
      display_name: 'Alert Acknowledgement Reasons',
      icon: 'fa fa-fw fa-exclamation-triangle',
      visible: true,
      isTitle: false,
    },
  ];

  public static PROPERTY_DATA_TYPE_LIST = [
    {
      name: 'Number',
      validations: ['minValue', 'maxValue', 'precision', 'units', 'defaultValue','required'],
    },
    {
      name: 'Boolean',
      validations: ['trueValue', 'falseValue', 'defaultValue','required'],
    },
    {
      name: 'String',
      validations: ['minLength', 'maxLength', 'units', 'defaultValue','required'],
    },
    {
      name: 'Enum',
      validations: ['enum', 'defaultValue','required'],
    },
    {
      name: 'Array',
      validations: ['required'],
    },
  ];

  public static DATE_OPTIONS = {
    'Last 5 Mins': [datefns.subMinutes(new Date(), 5), datefns.subSeconds(new Date(), 0)],
    'Last 30 Mins': [datefns.subMinutes(new Date(), 30), datefns.subSeconds(new Date(), 0)],
    'Last 1 Hour': [datefns.subHours(new Date(), 1), datefns.subSeconds(new Date(), 0)],
    'Last 3 Hours': [datefns.subHours(new Date(), 3), datefns.subSeconds(new Date(), 0)],
    'Last 6 Hours': [datefns.subHours(new Date(), 6), datefns.subSeconds(new Date(), 0)],
    'Last 12 Hours': [datefns.subHours(new Date(), 12), datefns.subSeconds(new Date(), 0)],
    'Last 24 Hours': [datefns.subHours(new Date(), 24), datefns.subSeconds(new Date(), 0)],
    'Today': [datefns.startOfDay(new Date()), datefns.subSeconds(new Date(), 0)],
    'Yesterday': [datefns.startOfDay(datefns.subDays(new Date(), 1)), datefns.endOfDay(datefns.subDays(new Date(), 1))],
    'This Week': [datefns.startOfWeek(new Date(), { weekStartsOn: 1 }), datefns.subSeconds(new Date(), 0)],
    'Last Week': [datefns.subWeeks(datefns.startOfISOWeek(new Date()), 1), datefns.subWeeks(datefns.endOfISOWeek(new Date()), 1)],
    'Last 30 Days': [datefns.subDays(new Date(), 29), datefns.subSeconds(new Date(), 0)],
    'This Month': [datefns.startOfMonth(new Date()), datefns.subSeconds(new Date(), 0)],
    'Last Month': [datefns.subMonths(datefns.startOfMonth(new Date()), 1), datefns.subMonths(datefns.endOfMonth(new Date()), 1)]
  };


  public static USER_DETAILS = 'userData';
  public static SELECTED_APP_DATA = 'selectedAppData';
  public static HIERARCHY_TAGS = 'hierarchytags';
  public static ASSETS_LIST = 'assets_list';
  public static ALL_ASSETS_LIST = 'all_assets_list';
  public static ASSETS_GATEWAYS_LIST = 'assets_gateways_list';
  public static ASSET_MODELS_LIST = 'asset_models_list';
  public static ASSET_MODEL_DATA = 'asset_model_data';
  public static ASSET_LIST_FILTER_FOR_GATEWAY = 'assetListFilterObj';
  public static APP_USERS = 'application_users';
  public static EXPIRY_TIME = 'expiry_time';
  public static IP_ASSET = 'IoT Asset';
  public static IP_GATEWAY = 'IoT Gateway';
  public static NON_IP_ASSET = 'Legacy Asset';
  public static NOT_ALLOWED_SPECIAL_CHARS_NAME = [' ', '.', '$', '#'];
  public static PASSWORD_REGEX = '^(?=.*[A-Z])(?=.*[!@#$&*])(?=.*[0-9]).{8,20}$';
  public static EMAIL_REGEX =
    /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/;
  public static MAC_ADDRESS_REGEX = /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/;
  public static ONLY_NOS_AND_CHARS = /^[a-zA-Z]+[a-zA-Z0-9\s]+$/;
  public static APP_NAME_REGEX = /^([a-zA-Z]+([a-zA-Z0-9]*[\s]?[a-zA-Z0-9]+)*){3,}$/;
  public static APP_ADMIN_ROLE = 'App Admin';
  public static APP_VERSION = 'version';
  public static MAIN_MENU_FILTERS = 'main_menu_filter';
  public static CONTROL_PANEL_FILTERS = 'control_panel_filter';
  public static APP_TOKEN = 'app_token';
  public static REFRESH_TOKEN = 'refresh_token';
  public static GUEST_USER = 'guest_user_details';
  public static SYSTEM_RESERVED_KEYWORDS = ['asset_id', 'slave_id'];
  public static NO_OF_RECORDS = 500;
  public static DEFAULT_APP_ICON = environment.blobContainerName + '/default_app_icon.png';
  public static DEFAULT_APP_LOGO = environment.blobContainerName + '/default_app_logo.png';
  public static DEFAULT_HEADER_LOGO = environment.blobContainerName + '/app-media/logo.png';
  public static DEFAULT_MODEL_IMAGE = environment.blobContainerName + '/asset-model-media/asset.svg';
  public static METHODNAME_REGEX = /^[a-zA-Z0-9_]+$/;
  public static APP_LOGO_WIDTH = 1120;
  public static APP_LOGO_HEIGHT = 480;
  public static APP_LOGO_SIZE = 1500000;
  public static APP_ICON_WIDTH = 560;
  public static APP_ICON_HEIGHT = 560;
  public static APP_ICON_SIZE = 1000000;
  public static ASSET_STATUS_ICON_WIDTH = 200;
  public static ASSET_STATUS_ICON_HEIGHT = 200;
  public static ASSET_STATUS_ICON_SIZE = 1000000;
  public static ASSET_MODEL_IMAGE_WIDTH = 2000;
  public static ASSET_MODEL_IMAGE_HEIGHT = 2000;
  public static ASSET_MODEL_IMAGE_SIZE = 2000000;
  public static DEFAULT_WHITELISTED_EXCEL_FILE = 'WhiteListedAssets_KPIX.xlsx';
  public static TIME_ZONES = [
    { "label": "International Date Line West (Etc/GMT+12)", "value": "-12:00" },
    { "label": "Midway Island, Samoa (Pacific/Midway)", "value": "-11:00" },
    { "label": "Hawaii (Pacific/Honolulu)", "value": "-10:00" },
    { "label": "Alaska (US/Alaska)", "value": "-09:00" },
    { "label": "Pacific Time (US & Canada) (America/Los_Angeles)", "value": "-08:00" },
    { "label": "Tijuana, Baja California (America/Tijuana)", "value": "-08:00" },
    { "label": "Arizona (US/Arizona)", "value": "-07:00" },
    { "label": "Chihuahua, La Paz, Mazatlan (America/Chihuahua)", "value": "-07:00" },
    { "label": "Mountain Time (US & Canada) (US/Mountain)", "value": "-07:00" },
    { "label": "Central America (America/Managua)", "value": "-06:00" },
    { "label": "Central Time (US & Canada) (US/Central)", "value": "-06:00" },
    { "label": "Guadalajara, Mexico City, Monterrey (America/Mexico_City)", "value": "-06:00" },
    { "label": "Saskatchewan (Canada/Saskatchewan)", "value": "-06:00" },
    { "label": "Bogota, Lima, Quito, Rio Branco (America/Bogota)", "value": "-05:00" },
    { "label": "Eastern Time (US & Canada) (US/Eastern)", "value": "-05:00" },
    { "label": "Indiana (East) (US/East-Indiana)", "value": "-05:00" },
    { "label": "Atlantic Time (Canada) (Canada/Atlantic)", "value": "-04:00" },
    { "label": "Caracas, La Paz (America/Caracas)", "value": "-04:00" },
    { "label": "Manaus (America/Manaus)", "value": "-04:00" },
    { "label": "Santiago (America/Santiago)", "value": "-04:00" },
    { "label": "Newfoundland (Canada/Newfoundland)", "value": "-03:30" },
    { "label": "Brasilia (America/Sao_Paulo)", "value": "-03:00" },
    { "label": "Buenos Aires, Georgetown (America/Argentina/Buenos_Aires)", "value": "-03:00" },
    { "label": "Greenland (America/Godthab)", "value": "-03:00" },
    { "label": "Montevideo (America/Montevideo)", "value": "-03:00" },
    { "label": "Mid-Atlantic (America/Noronha)", "value": "-02:00" },
    { "label": "Cape Verde Is. (Atlantic/Cape_Verde)", "value": "-01:00" },
    { "label": "Azores (Atlantic/Azores)", "value": "-01:00" },
    { "label": "Casablanca, Monrovia, Reykjavik (Africa/Casablanca)", "value": "+00:00" },
    { "label": "Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London (Etc/Greenwich)", "value": "+00:00" },
    { "label": "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna (Europe/Amsterdam)", "value": "+01:00" },
    { "label": "Belgrade, Bratislava, Budapest, Ljubljana, Prague (Europe/Belgrade)", "value": "+01:00" },
    { "label": "Brussels, Copenhagen, Madrid, Paris (Europe/Brussels)", "value": "+01:00" },
    { "label": "Sarajevo, Skopje, Warsaw, Zagreb (Europe/Sarajevo)", "value": "+01:00" },
    { "label": "West Central Africa (Africa/Lagos)", "value": "+01:00" },
    { "label": "Amman (Asia/Amman)", "value": "+02:00" },
    { "label": "Athens, Bucharest, Istanbul (Europe/Athens)", "value": "+02:00" },
    { "label": "Beirut (Asia/Beirut)", "value": "+02:00" },
    { "label": "Cairo (Africa/Cairo)", "value": "+02:00" },
    { "label": "Harare, Pretoria (Africa/Harare)", "value": "+02:00" },
    { "label": "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius (Europe/Helsinki)", "value": "+02:00" },
    { "label": "Jerusalem (Asia/Jerusalem)", "value": "+02:00" },
    { "label": "Minsk (Europe/Minsk)", "value": "+02:00" },
    { "label": "Windhoek (Africa/Windhoek)", "value": "+02:00" },
    { "label": "Kuwait, Riyadh, Baghdad (Asia/Kuwait)", "value": "+03:00" },
    { "label": "Moscow, St. Petersburg, Volgograd (Europe/Moscow)", "value": "+03:00" },
    { "label": "Nairobi (Africa/Nairobi)", "value": "+03:00" },
    { "label": "Tbilisi (Asia/Tbilisi)", "value": "+03:00" },
    { "label": "Tehran (Asia/Tehran)", "value": "+03:30" },
    { "label": "Abu Dhabi, Muscat (Asia/Muscat)", "value": "+04:00" },
    { "label": "Baku (Asia/Baku)", "value": "+04:00" },
    { "label": "Yerevan (Asia/Yerevan)", "value": "+04:00" },
    { "label": "Kabul (Asia/Kabul)", "value": "+04:30" },
    { "label": "Yekaterinburg (Asia/Yekaterinburg)", "value": "+05:00" },
    { "label": "Islamabad, Karachi, Tashkent (Asia/Karachi)", "value": "+05:00" },
    { "label": "Chennai, Kolkata, Mumbai, New Delhi (Asia/Calcutta)", "value": "+05:30" },
    { "label": "Sri Jayawardenapura (Asia/Calcutta)", "value": "+05:30" },
    { "label": "Kathmandu (Asia/Katmandu)", "value": "+05:45" },
    { "label": "Almaty, Novosibirsk (Asia/Almaty)", "value": "+06:00" },
    { "label": "Astana, Dhaka (Asia/Dhaka)", "value": "+06:00" },
    { "label": "Yangon (Rangoon) (Asia/Rangoon)", "value": "+06:30" },
    { "label": "Bangkok, Hanoi, Jakarta (Asia/Bangkok)", "value": "+07:00" },
    { "label": "Krasnoyarsk (Asia/Krasnoyarsk)", "value": "+07:00" },
    { "label": "Beijing, Chongqing, Hong Kong, Urumqi (Asia/Hong_Kong)", "value": "+08:00" },
    { "label": "Kuala Lumpur, Singapore (Asia/Kuala_Lumpur)", "value": "+08:00" },
    { "label": "Irkutsk, Ulaan Bataar (Asia/Irkutsk)", "value": "+08:00" },
    { "label": "Perth (Australia/Perth)", "value": "+08:00" },
    { "label": "Taipei (Asia/Taipei)", "value": "+08:00" },
    { "label": "Osaka, Sapporo, Tokyo (Asia/Tokyo)", "value": "+09:00" },
    { "label": "Seoul (Asia/Seoul)", "value": "+09:00" },
    { "label": "Yakutsk (Asia/Yakutsk)", "value": "+09:00" },
    { "label": "Adelaide (Australia/Adelaide)", "value": "+09:30" },
    { "label": "Darwin (Australia/Darwin)", "value": "+09:30" },
    { "label": "Brisbane (Australia/Brisbane)", "value": "+10:00" },
    { "label": "Canberra, Melbourne, Sydney (Australia/Canberra)", "value": "+10:00" },
    { "label": "Hobart (Australia/Hobart)", "value": "+10:00" },
    { "label": "Guam, Port Moresby (Pacific/Guam)", "value": "+10:00" },
    { "label": "Vladivostok (Asia/Vladivostok)", "value": "+10:00" },
    { "label": "Magadan, Solomon Is., New Caledonia (Asia/Magadan)", "value": "+11:00" },
    { "label": "Auckland, Wellington (Pacific/Auckland)", "value": "+12:00" },
    { "label": "Fiji, Kamchatka, Marshall Is. (Pacific/Fiji)", "value": "+12:00" },
    { "label": "Nuku'alofa (Pacific/Tongatapu)", "value": "+13:00" }
  ]
}
