build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - npm install
    #- ng test --code-coverage --watch=false
    - sonar-scanner
    - echo "Build Azure RDM UI complete..."
